### ISSUE TITLE
Linux için UI fix

### ISSUE THREAD

**Issue by ttbilgin** [deniz-ozcan/Pynar-Flowchart#12]
Pynar'a entegre edilmiş flowchart'ı Pardus 21'de çalıştırınca "waiting" animasyonu penceresindeki fontlar pencereye sığmıyor. Bunu biraz daha küçültmek veya pencereyi biraz daha büyütmek iyi olabilir. Bu sorun windows'ta yok, ama linuxta css ile ilgili böyle şeyler olabiliyor. 

![2022-09-06_23-39-54](https://user-images.githubusercontent.com/854154/188734203-cca93b68-9b16-4fd2-8daa-fcf6db1f92f8.png)

**Comment by deniz-ozcan** [comment]
https://github.com/deniz-ozcan/Pynar-Flowchart/blob/main/flower.py 
yazdığınız üç hatayı da düzelttiğim flower.py dosyasını indirip size en son attığım dosyadaki flowchart klasöründe bulunan flower.py dosyası ile değiştirmeniz halinde çözülecektirler.

**Comment by ttbilgin** [comment]
tamam düzelmiş, ufak bir pardus sorunu vardı onu ben commit ettim şunu incelersin [6fc0c12](https://github.com/deniz-ozcan/Pynar-Flowchart/commit/6fc0c1257938735696a74f1582b5642613bec562)
